apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shifts-php
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shifts-php
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
